spring:
  config:
    activate:
      on-profile: local

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${LOCAL_AUTH_SERVICE_URL}
          predicates:
            - Path=/api/v1/auth/**

        - id: user-service
          uri: ${LOCAL_USER_SERVICE_URL}
          predicates:
            - Path=/api/v1/users/**,/api/v1/cards/**
          filters:
            - JwtAuthFilter

        - id: order-service
          uri: ${LOCAL_ORDER_SERVICE_URL}
          predicates:
            - Path=/api/v1/orders/**,/api/v1/items/**
          filters:
            - JwtAuthFilter

server:
  port: ${LOCAL_SERVER_PORT}