apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  SPRING_PROFILES_ACTIVE: "docker"
  DOCKER_SERVER_PORT: "8085"

  DOCKER_AUTH_SERVICE_URL: "http://auth-service:8081"
  DOCKER_USER_SERVICE_URL: "http://user-service:8080"
  DOCKER_ORDER_SERVICE_URL: "http://order-service:8082"
  DOCKER_PAYMENT_SERVICE_URL: "http://payment-service:8084"
