apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  SPRING_PROFILES_ACTIVE: "docker"
  POSTGRES_DB: "auth_service_db"
  DOCKER_POSTGRES_URL: "jdbc:postgresql://auth-postgres:5432/auth_service_db"
  DOCKER_POSTGRES_USER: "postgres"

  JWT_ACCESS_TOKEN_EXPIRATION: "9000000"
  JWT_REFRESH_TOKEN_EXPIRATION: "2592000000"

  DOCKER_API_GATEWAY_URL: "http://api-gateway:8085"
