spring:
  datasource:
    url: ${DOCKER_POSTGRES_URL}
    username: ${DOCKER_POSTGRES_USER}
    password: ${DOCKER_POSTGRES_PASSWORD}
  jpa:
    show-sql: false
  liquibase:
    enabled: true
  data:
    redis:
      host: ${DOCKER_REDIS_HOST}
      port: ${DOCKER_REDIS_PORT}
  config:
    activate:
      on-profile: docker

app:
  auth-service:
    url: ${DOCKER_AUTH_SERVICE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always