version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: order-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - order-pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: order-redis
    ports:
      - "6380:6379"

  order-service:
    build: .
    container_name: order-service
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8082"

volumes:
  order-pgdata:
