apiVersion: v1
kind: Secret
metadata:
  name: order-secret
type: Opaque
stringData:
  DOCKER_POSTGRES_PASSWORD: "12345"
  JWT_SECRET: "w3HXH7eWA3-I8cq3wxygu8p52Jffvb6dnQXw0kT+uzaRWDgoHYMiNQzVD6Q-vmqd"
