spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${LOCAL_POSTGRES_URL}
    username: ${LOCAL_POSTGRES_USER}
    password: ${LOCAL_POSTGRES_PASSWORD}
  jpa:
    show-sql: true

server:
  port: 8083

app:
  user-service:
    url: ${LOCAL_USER_SERVICE_URL}