version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: auth-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - auth-pgdata:/var/lib/postgresql/data

  auth-service:
    build: .
    container_name: auth-service
    depends_on:
      - postgres
    env_file:
      - ./.env
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8081"

volumes:
  auth-pgdata: