apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
data:
  SPRING_PROFILES_ACTIVE: "docker"

  DOCKER_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  DOCKER_MONGO_URI: "mongodb://mongo:27017/payment_db"

  RANDOM_API_URL: "http://www.randomnumberapi.com/api/v1.0/random?min=1&max=100&count=1"